name: changshenkaiscsk

on:
  workflow_dispatch:
  schedule:
    - cron: '2 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: changshenkaiscsk
        env:
          u908: ${{ secrets.u908 }}
        run: |
          echo $u908 | jq -r .shaz361 | /bin/bash
          echo $kysr1830 | jq -r .sq9 | /bin/bash
          echo $ow051 | jq -r .ir14053 | /bin/bash

